<?php
namespace Database\Seeders;
use App\Models\Client\Client;use App\Models\Product\Product;use App\Models\User;use App\Models\Setting\Setting;use App\Models\Presentation\Presentation;use App\Services\Presentation\PresentationBuilderService;use Illuminate\Database\Seeder;use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder {public function run():void{
 $admin=User::updateOrCreate(['email'=>'admin@example.com'],['name'=>'Administrator','password'=>Hash::make('Admin@12345'),'role'=>'super_admin','status'=>'active','phone'=>'']);
 foreach(['company_name'=>'Your Software Company','company_tagline'=>'Business software, built around your workflow.','company_email'=>'sales@example.com','company_phone'=>'+91 00000 00000','company_whatsapp'=>'910000000000','company_address'=>'India','company_about'=>'We design and deliver reliable web and mobile software solutions with practical implementation and ongoing support.','privacy_notice'=>'This private presentation records page visits, section engagement, button clicks, device/browser information and approximate network location for security and sales analytics.'] as $k=>$v) Setting::updateOrCreate(['key'=>$k],['group'=>'company','value'=>$v]);
 $client=Client::firstOrCreate(['company_name'=>'Demo Client Pvt. Ltd.'],['contact_name'=>'Demo Contact','email'=>'demo.client@example.com','phone'=>'9999999999','city'=>'Pune','state'=>'Maharashtra','status'=>'prospect','owner_id'=>$admin->id]);
 $product=Product::firstOrCreate(['slug'=>'dairy-management-system'],['name'=>'Dairy Management System','category'=>'Business Software','tagline'=>'One connected platform for complete dairy operations','summary'=>'Manage farmers, animals, milk, feeding, breeding, veterinary workflows and reporting in one platform.','description'=>'A configurable web and mobile software platform designed to centralize daily operations, improve visibility and reduce manual work.','base_price'=>100000,'currency'=>'INR','default_timeline_days'=>45,'status'=>'active']);
 foreach([['Farmer Management','Central farmer profiles, animals, transactions and history.'],['Animal Management','Track animal lifecycle, health and breeding information.'],['Milk Collection','Record morning/evening milk with centralized reporting.'],['Reports & Analytics','Management dashboards and operational reports.']] as $i=>$f)$product->features()->firstOrCreate(['title'=>$f[0]],['description'=>$f[1],'icon'=>'ri-checkbox-circle-line','sort_order'=>($i+1)*10]);
 $p=Presentation::firstOrCreate(['reference_no'=>'SP-DEMO-001'],['client_id'=>$client->id,'product_id'=>$product->id,'owner_id'=>$admin->id,'public_token'=>'demo-presentation-'.strtolower(str()->random(20)),'title'=>'Dairy Management Software Solution','status'=>'published','price'=>100000,'currency'=>'INR','intro_message'=>'Prepared exclusively for Demo Client Pvt. Ltd.','client_requirements'=>'Centralized management, mobile accessibility and clear operational reporting.','recommended_solution'=>'A connected admin platform with mobile workflows and role-based access.','deliverables'=>'Admin panel\nWeb platform\nMobile-ready workflows\nDeployment\nTraining','implementation_timeline'=>'Requirement confirmation\nConfiguration\nCustomization\nTesting\nDeployment\nTraining','support_details'=>'Implementation assistance, training and post-deployment support.','terms'=>'Commercial terms and final scope are subject to written confirmation.','valid_until'=>now()->addDays(30),'published_at'=>now()]);
 app(PresentationBuilderService::class)->createDefaults($p);
 }}
