-- Client Sales Presentation Portal - MySQL / MariaDB fallback installer
-- Preferred installation: php artisan migrate --seed --force
-- Fallback: create an empty database, select it in phpMyAdmin, then import this file.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `migrations` (`id` int unsigned NOT NULL AUTO_INCREMENT,`migration` varchar(255) NOT NULL,`batch` int NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) NOT NULL,`email` varchar(255) NOT NULL,`email_verified_at` timestamp NULL,`password` varchar(255) NOT NULL,`remember_token` varchar(100) NULL,`created_at` timestamp NULL,`updated_at` timestamp NULL,`role` varchar(40) NOT NULL DEFAULT 'salesperson',`status` varchar(20) NOT NULL DEFAULT 'active',`phone` varchar(30) NULL,`photo` varchar(255) NULL,`last_login_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `users_email_unique` (`email`),KEY `users_role_index` (`role`),KEY `users_status_index` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_reset_tokens` (`email` varchar(255) NOT NULL,`token` varchar(255) NOT NULL,`created_at` timestamp NULL,PRIMARY KEY (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sessions` (`id` varchar(255) NOT NULL,`user_id` bigint unsigned NULL,`ip_address` varchar(45) NULL,`user_agent` text NULL,`payload` longtext NOT NULL,`last_activity` int NOT NULL,PRIMARY KEY (`id`),KEY `sessions_user_id_index` (`user_id`),KEY `sessions_last_activity_index` (`last_activity`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache` (`key` varchar(255) NOT NULL,`value` mediumtext NOT NULL,`expiration` bigint NOT NULL,PRIMARY KEY (`key`),KEY `cache_expiration_index` (`expiration`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cache_locks` (`key` varchar(255) NOT NULL,`owner` varchar(255) NOT NULL,`expiration` bigint NOT NULL,PRIMARY KEY (`key`),KEY `cache_locks_expiration_index` (`expiration`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`queue` varchar(255) NOT NULL,`payload` longtext NOT NULL,`attempts` smallint unsigned NOT NULL,`reserved_at` int unsigned NULL,`available_at` int unsigned NOT NULL,`created_at` int unsigned NOT NULL,PRIMARY KEY (`id`),KEY `jobs_queue_index` (`queue`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_batches` (`id` varchar(255) NOT NULL,`name` varchar(255) NOT NULL,`total_jobs` int NOT NULL,`pending_jobs` int NOT NULL,`failed_jobs` int NOT NULL,`failed_job_ids` longtext NOT NULL,`options` mediumtext NULL,`cancelled_at` int NULL,`created_at` int NOT NULL,`finished_at` int NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `failed_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`uuid` varchar(255) NOT NULL,`connection` varchar(255) NOT NULL,`queue` varchar(255) NOT NULL,`payload` longtext NOT NULL,`exception` longtext NOT NULL,`failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`),KEY `failed_jobs_connection_queue_failed_at_index` (`connection`,`queue`,`failed_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `clients` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`company_name` varchar(255) NOT NULL,`contact_name` varchar(255) NULL,`email` varchar(255) NULL,`phone` varchar(30) NULL,`whatsapp` varchar(30) NULL,`city` varchar(255) NULL,`state` varchar(255) NULL,`country` varchar(255) NOT NULL DEFAULT 'India',`status` varchar(30) NOT NULL DEFAULT 'prospect',`notes` text NULL,`owner_id` bigint unsigned NULL,`created_at` timestamp NULL,`updated_at` timestamp NULL,`deleted_at` timestamp NULL,PRIMARY KEY (`id`),KEY `clients_email_index` (`email`),KEY `clients_phone_index` (`phone`),KEY `clients_city_index` (`city`),KEY `clients_state_index` (`state`),KEY `clients_status_index` (`status`),KEY `clients_owner_id_foreign` (`owner_id`),CONSTRAINT `clients_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `products` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) NOT NULL,`slug` varchar(255) NOT NULL,`category` varchar(255) NULL,`tagline` varchar(255) NULL,`summary` text NULL,`description` longtext NULL,`base_price` decimal(14,2) NULL,`currency` varchar(8) NOT NULL DEFAULT 'INR',`default_timeline_days` int unsigned NULL,`cover_image` varchar(255) NULL,`status` varchar(20) NOT NULL DEFAULT 'active',`created_at` timestamp NULL,`updated_at` timestamp NULL,`deleted_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `products_slug_unique` (`slug`),KEY `products_category_index` (`category`),KEY `products_status_index` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `product_features` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`product_id` bigint unsigned NOT NULL,`title` varchar(255) NOT NULL,`description` text NULL,`icon` varchar(80) NULL,`sort_order` int unsigned NOT NULL DEFAULT 0,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),KEY `product_features_product_id_foreign` (`product_id`),CONSTRAINT `product_features_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `product_media` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`product_id` bigint unsigned NOT NULL,`title` varchar(255) NULL,`type` varchar(20) NOT NULL DEFAULT 'image',`file_path` varchar(255) NULL,`external_url` text NULL,`sort_order` int unsigned NOT NULL DEFAULT 0,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),KEY `product_media_product_id_foreign` (`product_id`),CONSTRAINT `product_media_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `product_demo_links` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`product_id` bigint unsigned NOT NULL,`label` varchar(255) NOT NULL,`url` text NOT NULL,`username` varchar(255) NULL,`password` text NULL,`type` varchar(30) NOT NULL DEFAULT 'website',`sort_order` int unsigned NOT NULL DEFAULT 0,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),KEY `product_demo_links_product_id_foreign` (`product_id`),CONSTRAINT `product_demo_links_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `leads` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`client_id` bigint unsigned NULL,`product_id` bigint unsigned NULL,`owner_id` bigint unsigned NULL,`title` varchar(255) NOT NULL,`source` varchar(40) NULL,`status` varchar(30) NOT NULL DEFAULT 'new',`priority` varchar(20) NOT NULL DEFAULT 'medium',`expected_value` decimal(14,2) NULL,`next_follow_up_at` date NULL,`requirement` text NULL,`notes` text NULL,`created_at` timestamp NULL,`updated_at` timestamp NULL,`deleted_at` timestamp NULL,PRIMARY KEY (`id`),KEY `leads_client_id_foreign` (`client_id`),KEY `leads_product_id_foreign` (`product_id`),KEY `leads_owner_id_foreign` (`owner_id`),KEY `leads_source_index` (`source`),KEY `leads_status_index` (`status`),KEY `leads_priority_index` (`priority`),KEY `leads_next_follow_up_at_index` (`next_follow_up_at`),CONSTRAINT `leads_client_id_foreign` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE SET NULL,CONSTRAINT `leads_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL,CONSTRAINT `leads_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `follow_ups` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`lead_id` bigint unsigned NOT NULL,`user_id` bigint unsigned NULL,`follow_up_at` datetime NOT NULL,`type` varchar(30) NOT NULL DEFAULT 'call',`status` varchar(20) NOT NULL DEFAULT 'pending',`notes` text NULL,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),KEY `follow_ups_lead_id_foreign` (`lead_id`),KEY `follow_ups_user_id_foreign` (`user_id`),KEY `follow_ups_follow_up_at_index` (`follow_up_at`),KEY `follow_ups_status_index` (`status`),CONSTRAINT `follow_ups_lead_id_foreign` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,CONSTRAINT `follow_ups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `presentations` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`client_id` bigint unsigned NOT NULL,`product_id` bigint unsigned NOT NULL,`owner_id` bigint unsigned NULL,`reference_no` varchar(255) NOT NULL,`public_token` varchar(64) NOT NULL,`title` varchar(255) NOT NULL,`status` varchar(30) NOT NULL DEFAULT 'draft',`price` decimal(14,2) NULL,`currency` varchar(8) NOT NULL DEFAULT 'INR',`intro_message` text NULL,`client_requirements` longtext NULL,`recommended_solution` longtext NULL,`deliverables` longtext NULL,`implementation_timeline` longtext NULL,`support_details` longtext NULL,`terms` longtext NULL,`valid_until` date NULL,`published_at` timestamp NULL,`engagement_score` tinyint unsigned NOT NULL DEFAULT 0,`created_at` timestamp NULL,`updated_at` timestamp NULL,`deleted_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `presentations_reference_no_unique` (`reference_no`),UNIQUE KEY `presentations_public_token_unique` (`public_token`),KEY `presentations_client_id_foreign` (`client_id`),KEY `presentations_product_id_foreign` (`product_id`),KEY `presentations_owner_id_foreign` (`owner_id`),KEY `presentations_status_index` (`status`),KEY `presentations_engagement_score_index` (`engagement_score`),CONSTRAINT `presentations_client_id_foreign` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,CONSTRAINT `presentations_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,CONSTRAINT `presentations_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `presentation_sections` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`presentation_id` bigint unsigned NOT NULL,`section_key` varchar(60) NOT NULL,`custom_title` varchar(255) NULL,`custom_content` longtext NULL,`settings` json NULL,`sort_order` int unsigned NOT NULL DEFAULT 0,`is_enabled` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `presentation_sections_presentation_id_section_key_unique` (`presentation_id`,`section_key`),CONSTRAINT `presentation_sections_presentation_id_foreign` FOREIGN KEY (`presentation_id`) REFERENCES `presentations` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `presentation_sessions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`presentation_id` bigint unsigned NOT NULL,`session_uuid` char(36) NOT NULL,`visitor_uuid` char(36) NULL,`ip_address` varchar(64) NULL,`country` varchar(100) NULL,`city` varchar(120) NULL,`device_type` varchar(30) NULL,`browser` varchar(60) NULL,`operating_system` varchar(60) NULL,`user_agent` text NULL,`referrer` text NULL,`source` varchar(60) NULL,`current_section` varchar(60) NULL,`started_at` timestamp NULL,`last_activity_at` timestamp NULL,`ended_at` timestamp NULL,`active_seconds` bigint unsigned NOT NULL DEFAULT 0,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `presentation_sessions_session_uuid_unique` (`session_uuid`),KEY `presentation_sessions_presentation_id_foreign` (`presentation_id`),KEY `presentation_sessions_visitor_uuid_index` (`visitor_uuid`),KEY `presentation_sessions_device_type_index` (`device_type`),KEY `presentation_sessions_source_index` (`source`),KEY `presentation_sessions_last_activity_at_index` (`last_activity_at`),CONSTRAINT `presentation_sessions_presentation_id_foreign` FOREIGN KEY (`presentation_id`) REFERENCES `presentations` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `presentation_events` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`presentation_id` bigint unsigned NOT NULL,`session_id` bigint unsigned NULL,`event_type` varchar(60) NOT NULL,`section_key` varchar(60) NULL,`element_key` varchar(120) NULL,`target_url` text NULL,`duration_ms` int unsigned NULL,`meta` json NULL,`occurred_at` timestamp NOT NULL,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),KEY `presentation_events_presentation_id_foreign` (`presentation_id`),KEY `presentation_events_session_id_foreign` (`session_id`),KEY `presentation_events_event_type_index` (`event_type`),KEY `presentation_events_section_key_index` (`section_key`),KEY `presentation_events_element_key_index` (`element_key`),KEY `presentation_events_occurred_at_index` (`occurred_at`),KEY `presentation_events_presentation_id_occurred_at_index` (`presentation_id`,`occurred_at`),CONSTRAINT `presentation_events_presentation_id_foreign` FOREIGN KEY (`presentation_id`) REFERENCES `presentations` (`id`) ON DELETE CASCADE,CONSTRAINT `presentation_events_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `presentation_sessions` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `settings` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`group` varchar(50) NOT NULL DEFAULT 'general',`key` varchar(255) NOT NULL,`value` longtext NULL,`type` varchar(30) NOT NULL DEFAULT 'text',`is_public` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL,`updated_at` timestamp NULL,PRIMARY KEY (`id`),UNIQUE KEY `settings_key_unique` (`key`),KEY `settings_group_index` (`group`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`migration`,`batch`) VALUES
('0001_01_01_000000_create_users_table',1),('0001_01_01_000001_create_cache_table',1),('0001_01_01_000002_create_jobs_table',1),('2026_08_22_000100_add_sales_fields_to_users_table',1),('2026_08_22_000200_create_sales_portal_tables',1);
INSERT INTO `users` (`name`,`email`,`password`,`role`,`status`,`created_at`,`updated_at`) VALUES ('Administrator','admin@example.com','$2y$12$XeF8.rbOYb0n0SE2kGMc8OM059YtOl8C2m/rfSnBOsU.Tj1xbBRyq','super_admin','active',NOW(),NOW());
INSERT INTO `settings` (`group`,`key`,`value`,`created_at`,`updated_at`) VALUES
('company','company_name','Your Software Company',NOW(),NOW()),
('company','company_tagline','Business software, built around your workflow.',NOW(),NOW()),
('company','company_email','sales@example.com',NOW(),NOW()),
('company','company_phone','+91 00000 00000',NOW(),NOW()),
('company','company_whatsapp','910000000000',NOW(),NOW()),
('company','company_address','India',NOW(),NOW()),
('company','company_about','We design and deliver reliable web and mobile software solutions with practical implementation and ongoing support.',NOW(),NOW()),
('company','privacy_notice','This private presentation records page visits, section engagement, button clicks, device/browser information and approximate network location for security and sales analytics.',NOW(),NOW());

SET FOREIGN_KEY_CHECKS=1;
